// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcgNFWOvVpsXYqKXc27cLOMAHfGG-7Dck',
    appId: '1:201125706939:android:658c9550a8defc89ab3d9e',
    messagingSenderId: '201125706939',
    projectId: 'blog-app-f2ee1',
    storageBucket: 'blog-app-f2ee1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbmDwy0RJtPz-_9vgZe-CHIi2_r2AM9dA',
    appId: '1:201125706939:ios:f4b3f6c286b591a5ab3d9e',
    messagingSenderId: '201125706939',
    projectId: 'blog-app-f2ee1',
    storageBucket: 'blog-app-f2ee1.firebasestorage.app',
    androidClientId:
        '201125706939-u20ah65u8hrrveg99j9hea310q8ko608.apps.googleusercontent.com',
    iosClientId:
        '201125706939-3teen60ra7j33arqoq6r68pocgm92ggl.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );
}
